project:
  type: website

website:
  title: "CalGRO-Dashboard"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: testdashboard.qmd
        text: Recharge
      - href: SecondDashboard.qmd
        text: Water depth
      - href: ThirdDashboard.qmd
        text: Las Piletas


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



