project:
  type: website

website:
  title: "CalGRO-Dashboard"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: FourthDashboard
        text: Maps
      - href: ThirdDashboard.qmd
        text: Las Piletas
      - href: fifthdashboard.qmd
        text: Recharge Calculations
      - href: Rain_intensity_well_rise_scatter.qmd
        text: Rainfall and Well Depth
      - href: python_code_test.qmd
        text: Rendering Python Data



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



