project:
  type: website

website:
  title: "CalGRO-Dashboard"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: testdashboard.qmd
        text: Dashboard
      - href: SecondDashboard.qmd
        text: Dashboard two


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



